export const data = [
    {
        id: 1,
        photo: 'https://s26162.pcdn.co/wp-content/uploads/2017/05/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Drama',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Mohammed',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Accepted',
        userStatus: 'Approved',
    },
    {
        id: 2,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Ali',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Accepted',
        userStatus: 'Disapproved',
    },
    {
        id: 3,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Lora',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Accepted',
        userStatus: 'Approved',
    },
    {
        id: 4,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Ahmed',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Accepted',
        userStatus: 'Approved',
    },
    {
        id: 5,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Nadia',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Rejected',
        userStatus: 'Disapproved',
    },
    {
        id: 6,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Layla',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Rejected',
        userStatus: 'Disapproved',
    },
    {
        id: 7,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Joseph',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Rejected',
        userStatus: 'Pending',
    },
    {
        id: 8,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Sara',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
    {
        id: 9,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Lola',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
    {
        id: 10,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Essam',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
    {
        id: 11,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Badr',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
    {
        id: 12,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Khaled',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    }, {
        id: 13,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Sora',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
    {
        id: 14,
        photo: '/the-lord-of-the-rings-book-cover.jpg',
        title: 'lordftherings',
        author: 'abraham lincolin',
        category: 'Action',
        rackNumber: '23',
        ISBN: '452-143-5687',
        userName: 'Barak',
        userEmail: 'Something@gmail.com',
        userPhoneNum: '123 456 7890',
        borrowStatus: 'Pending',
        userStatus: 'Pending',
    },
];


export const findById = ({ params }) => {
    const key = JSON.parse(params.id);
    const oldData = data.find((item) => item.id === key)
    if (oldData) {
        return oldData;
    }
    return null
};